// Noise IK, device keys wrapped by the Android Keystore, and the paired-machine store (docs/adr/0005).
plugins {
    alias(libs.plugins.termbridge.android.library)
    alias(libs.plugins.termbridge.hilt)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "io.termbridge.core.crypto"
}

dependencies {
    // X25519, ChaCha20-Poly1305 and BLAKE2s primitives for Noise; R8 keeps only what is used.
    implementation(libs.bouncycastle.prov)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.androidx.datastore.preferences)

    testImplementation(libs.kotlinx.serialization.json)
    testImplementation(libs.kotlinx.coroutines.test)
}

tasks.withType<Test>().configureEach {
    // Golden Noise bytes generated by the Go agent (docs/PROTOCOL.md §1.2).
    val vectors = rootProject.file("../docs/vectors/noise.json")
    inputs.file(vectors).withPathSensitivity(PathSensitivity.RELATIVE)
    systemProperty("termbridge.noiseVectors", vectors.absolutePath)
}
