"""Generates frames.json: an independent (third) encoder that the Go and Kotlin codecs are both checked
against (PROTOCOL.md §7). Run from the repository root:  python3 docs/vectors/gen_frames.py > docs/vectors/frames.json
"""
import json, struct, sys

def wire(op, sid, payload): return (bytes([op, sid]) + payload).hex()
def js(obj): return json.dumps(obj, separators=(",", ":"), ensure_ascii=False).encode()

raw = []
def r(name, op, sid, payload):
    raw.append({"name": name, "op": op, "sid": sid, "payload_hex": payload.hex(), "wire_hex": wire(op, sid, payload)})
r("data_ascii", 0x01, 1, b"echo hello\r")
r("data_utf8", 0x01, 2, "سلام ✓\n".encode())
r("data_ansi_sgr", 0x01, 1, b"\x1b[1;32mok\x1b[0m\r\n")
r("data_empty", 0x01, 1, b"")
r("data_max_session_id", 0x01, 255, b"x")
r("unknown_opcode_passthrough", 0x7F, 0, b"\x01\x02")

typed = []
def t(name, kind, op, sid, payload, json_payload=False, **fields):
    v = {"name": name, "kind": kind, "sid": sid, **fields, "wire_hex": wire(op, sid, payload)}
    if json_payload: v["json"] = True
    typed.append(v)
t("resize_80x24", "resize", 0x02, 1, struct.pack(">HH", 80, 24), cols=80, rows=24)
t("resize_max", "resize", 0x02, 255, struct.pack(">HH", 65535, 65535), cols=65535, rows=65535)
t("session_opened", "session_opened", 0x11, 0, bytes([7]), new_sid=7)
t("session_close", "session_close", 0x12, 3, b"")
t("session_exit_zero", "session_exit", 0x13, 3, struct.pack(">i", 0), code=0)
t("session_exit_signal", "session_exit", 0x13, 3, struct.pack(">i", 130), code=130)
t("session_exit_negative", "session_exit", 0x13, 4, struct.pack(">i", -1), code=-1)
t("session_attach", "session_attach", 0x14, 2, struct.pack(">HH", 100, 30), cols=100, rows=30)
t("session_attached", "session_attached", 0x15, 2, b"")
t("ping", "ping", 0x20, 0, struct.pack(">Q", 1757851200123), ts="1757851200123")
t("pong", "pong", 0x21, 0, struct.pack(">Q", 1757851200123), ts="1757851200123")
t("ping_u64_max", "ping", 0x20, 0, struct.pack(">Q", 2**64 - 1), ts=str(2**64 - 1))
t("hello", "hello", 0x30, 0, js({"v": 1, "client": "android/0.1.0"}), True, v=1, client="android/0.1.0")
t("hello_ack", "hello_ack", 0x31, 0, js({"v": 1, "agent": "termbridge-agent/0.1.0", "os": "linux", "hostname": "amir-thinkpad"}), True,
  v=1, agent="termbridge-agent/0.1.0", os="linux", hostname="amir-thinkpad")
t("session_open_defaults", "session_open", 0x10, 0, js({"shell": "", "cwd": "", "cols": 80, "rows": 24}), True, shell="", cwd="", cols=80, rows=24)
t("session_open_custom", "session_open", 0x10, 0, js({"shell": "/bin/zsh", "cwd": "/tmp", "cols": 132, "rows": 43}), True, shell="/bin/zsh", cwd="/tmp", cols=132, rows=43)
t("error_connection", "error", 0x40, 0, js({"code": "too_many_sessions", "msg": "limit is 8"}), True, code="too_many_sessions", msg="limit is 8")
t("error_session", "error", 0x40, 9, js({"code": "bad_frame", "msg": "resize payload must be 4 bytes"}), True, code="bad_frame", msg="resize payload must be 4 bytes")
t("error_unknown_session", "error", 0x40, 4, js({"code": "unknown_session", "msg": "session 4 is gone"}), True, code="unknown_session", msg="session 4 is gone")

invalid = [
    {"name": "empty", "wire_hex": "", "error": "short_frame"},
    {"name": "one_byte", "wire_hex": "01", "error": "short_frame"},
    {"name": "resize_short", "wire_hex": "0201005000", "error": "bad_payload"},
    {"name": "resize_long", "wire_hex": "02010050001800", "error": "bad_payload"},
    {"name": "session_opened_empty", "wire_hex": "1100", "error": "bad_payload"},
    {"name": "session_opened_zero_id", "wire_hex": "110000", "error": "bad_payload"},
    {"name": "session_close_with_payload", "wire_hex": "120301", "error": "bad_payload"},
    {"name": "session_exit_short", "wire_hex": "1303000000", "error": "bad_payload"},
    {"name": "session_attach_short", "wire_hex": "140200", "error": "bad_payload"},
    {"name": "session_attached_with_payload", "wire_hex": "150201", "error": "bad_payload"},
    {"name": "ping_short", "wire_hex": "2000" + "00" * 7, "error": "bad_payload"},
    {"name": "hello_not_json", "wire_hex": "3000" + b"{nope".hex(), "error": "bad_payload"},
]
generated = [
    {"name": "max_payload_ok", "op": 1, "sid": 1, "payload_len": 65517, "fill": 97},
    {"name": "payload_too_large", "op": 1, "sid": 1, "payload_len": 65518, "fill": 97, "error": "frame_too_large"},
]
doc = {
    "comment": "Canonical TermBridge v1 frames. Generated by an independent encoder; see docs/PROTOCOL.md §7. "
               "Binary kinds must encode byte-for-byte to wire_hex; kinds with json=true are compared by value.",
    "protocol_version": 1,
    "max_payload": 65517,
    "raw": raw, "typed": typed, "invalid": invalid, "generated": generated,
}
json.dump(doc, sys.stdout, indent=2, ensure_ascii=False); sys.stdout.write("\n")
