package io.termbridge.core.crypto

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

/**
 * Reproduces docs/vectors/noise.json — generated by the Go agent with flynn/noise — byte for
 * byte, which proves the two Noise implementations interoperate.
 */
class NoiseVectorsTest {
    private val v: JsonObject = Json.parseToJsonElement(
        File(checkNotNull(System.getProperty("termbridge.noiseVectors")) { "termbridge.noiseVectors not set" }).readText(),
    ).jsonObject

    private fun hex(key: String) = unhex(v.getValue(key).jsonPrimitive.content)

    private fun unhex(s: String) = ByteArray(s.length / 2) { s.substring(2 * it, 2 * it + 2).toInt(16).toByte() }

    private fun key(privateHex: String) = hex(privateHex).let { KeyPair(it, X25519.publicKey(it)) }

    @Test
    fun agentIdMapsToNoiseStaticKey() {
        assertContentEquals(hex("agent_x25519_public_hex"), AgentKeys.noiseStaticKey(v.getValue("agent_id").jsonPrimitive.content))
    }

    @Test
    fun deviceStaticPublicKeyMatches() {
        assertContentEquals(hex("device_static_public_hex"), X25519.publicKey(hex("device_static_private_hex")))
    }

    @Test
    fun initiatorReproducesHandshakeAndTransport() {
        val agentStatic = AgentKeys.noiseStaticKey(v.getValue("agent_id").jsonPrimitive.content)
        val hs = NoiseIK(
            initiator = true,
            localStatic = key("device_static_private_hex"),
            remoteStatic = agentStatic,
            prologue = hex("prologue_hex"),
            ephemeral = { key("initiator_ephemeral_private_hex") },
        )
        assertContentEquals(hex("msg1_hex"), hs.writeMessage(hex("msg1_payload_hex")))
        assertContentEquals(ByteArray(0), hs.readMessage(hex("msg2_hex")))
        val transport = hs.split()
        for (m in v.getValue("transport").jsonArray.map { it.jsonObject }) {
            val plain = unhex(m.getValue("plaintext_hex").jsonPrimitive.content)
            val sealed = unhex(m.getValue("ciphertext_hex").jsonPrimitive.content)
            when (m.getValue("direction").jsonPrimitive.content) {
                "initiator_to_responder" -> assertContentEquals(sealed, transport.encrypt(plain))
                else -> assertContentEquals(plain, transport.decrypt(sealed))
            }
        }
    }

    @Test
    fun responderReproducesHandshakeAndTransport() {
        val agent = key("agent_x25519_private_hex")
        assertContentEquals(hex("agent_x25519_public_hex"), agent.public)
        val hs = NoiseIK(
            initiator = false,
            localStatic = agent,
            remoteStatic = null,
            prologue = hex("prologue_hex"),
            ephemeral = { key("responder_ephemeral_private_hex") },
        )
        assertContentEquals(hex("msg1_payload_hex"), hs.readMessage(hex("msg1_hex")))
        assertContentEquals(hex("device_static_public_hex"), hs.remoteStatic)
        assertContentEquals(hex("msg2_hex"), hs.writeMessage())
        val transport = hs.split()
        for (m in v.getValue("transport").jsonArray.map { it.jsonObject }) {
            val plain = unhex(m.getValue("plaintext_hex").jsonPrimitive.content)
            val sealed = unhex(m.getValue("ciphertext_hex").jsonPrimitive.content)
            when (m.getValue("direction").jsonPrimitive.content) {
                "responder_to_initiator" -> assertContentEquals(sealed, transport.encrypt(plain))
                else -> assertContentEquals(plain, transport.decrypt(sealed))
            }
        }
    }

    @Test
    fun kotlinRoundTripBothRoles() {
        val agent = X25519.generate()
        val phone = X25519.generate()
        val i = NoiseIK(true, phone, agent.public)
        val r = NoiseIK(false, agent, null)
        assertEquals("pair", r.readMessage(i.writeMessage("pair".encodeToByteArray())).decodeToString())
        assertContentEquals(phone.public, r.remoteStatic)
        i.readMessage(r.writeMessage())
        val (a, b) = i.split() to r.split()
        assertEquals("ls\r", b.decrypt(a.encrypt("ls\r".encodeToByteArray())).decodeToString())
        assertEquals("ok", a.decrypt(b.encrypt("ok".encodeToByteArray())).decodeToString())
        assertFailsWith<NoiseException> { b.decrypt(a.encrypt("x".encodeToByteArray()).also { it[0] = (it[0] + 1).toByte() }) }
    }

    @Test
    fun rejectsInvalidAgentIds() {
        assertFailsWith<NoiseException> { AgentKeys.noiseStaticKey("not base64!") }
        assertFailsWith<NoiseException> { AgentKeys.noiseStaticKey("AAAA") }
        // The Ed25519 identity point (y = 1): low order.
        val identity = java.util.Base64.getEncoder().encodeToString(ByteArray(32).also { it[0] = 1 })
        assertFailsWith<NoiseException> { AgentKeys.noiseStaticKey(identity) }
    }
}
